AllCops:
  TargetRubyVersion: 2.2

ClassLength:
  Max: 500

ModuleLength:
  Max: 500

Rails:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: true

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/IndentHash:
  EnforcedStyle: consistent

Style/WordArray:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/MutableConstant:
  Enabled: true

Performance/Casecmp:
  Enabled: true

Style/GuardClause:
  Enabled: true
