name: news-scraper

up:
  - ruby: 2.3.1
  - bundler

commands:
  rubocop:
    desc:   'Lint the Ruby code with Rubocop'
    run:    bundle exec rubocop
    aliases: [r, rubo, lint, l]
  test: bundle exec rake test