# All domains should include the scrape method/pattern for data_types

data_types:
  - "author"
  - "body"
  - "description"
  - "keywords"
  - "section"
  - "datetime"
  - "title"

# All data types must include :method and :pattern
#
presets:
  author:
    class: &class_author
      method: css
      pattern: ".author"
    id: &id_author
      method: css
      pattern: "#author"
    name: &name_author
      method: css
      pattern: ".author-name"
    link: &link_author
      method: xpath
      pattern: "//a[contains(@href, 'author')]"
    meta: &meta_author
      method: xpath
      pattern: "//meta[@name='author']/@content"
    rel_link: &rel_link_author
      method: xpath
      pattern: "//a[@rel='author']"
    vcard: &vcard_author
      method: css
      pattern: ".vcard .fn"
  body:
    readability: &readability_body
      method: "readability"
      pattern: ""
  description:
    meta: &meta_description
      method: "xpath"
      pattern: "//meta[@name='description']/@content"
    og: &og_description
      method: "xpath"
      pattern: "//meta[@property='og:description']/@content"
    metainspector: &metainspector_description
      method: 'metainspector'
      pattern: :description
  keywords:
    meta: &meta_keywords
      method: "xpath"
      pattern: "//meta[@name='keywords']/@content"
    article_tag: &article_tag_keywords
      method: "xpath"
      pattern: "//meta[@property='article:tag']/@content"
    news_keywords: &news_keywords_keywords
      method: "xpath"
      pattern: "//meta[@name='news_keywords']/@content"
    highscore: &highscore_keywords
      method: highscore
      pattern: ""
  section:
    meta: &meta_section
      method: "xpath"
      pattern: "//meta[@property='article:section']/@content"
    section: &section_section
      method: "xpath"
      pattern: "//meta[@name='section']/@content"
  datetime:
    article_date_original: &article_date_original_datetime
      method: xpath
      pattern: //meta[@name='article_date_original']/@content
    article_published_time: &article_published_time_datetime
      method: "xpath"
      pattern: "//meta[@property='article:published_time']/@content"
    date: &date_datetime
      method: xpath
      pattern: //meta[@name='date']/@content
    date_published: &date_published_datetime
      method: xpath
      pattern: //*[@itemprop='datePublished']/@datetime
    og_published_time: &og_published_time_datetime
      method: xpath
      pattern: //meta[@property='og:published_time']/@content
    original_publication_date: &original_publication_date_datetime
      method: xpath
      pattern: //meta[@name='OriginalPublicationDate']/@content
    publication_date: &publication_date_datetime
      method: xpath
      pattern: //meta[@name='publication_date']/@content
    publish_date: &publish_date_datetime
      method: xpath
      pattern: //meta[@name='PublishDate']/@content
    rnews_date_published: &rnews_date_published_datetime
      method: xpath
      pattern: //meta[@property='rnews:datePublished']/@content
    sailthru_date: &sailthru_date_datetime
      method: xpath
      pattern: //meta[@name='sailthru.date']/@content
    time: &time_datetime
      method: xpath
      pattern: //time/@datetime
    date_published_datetime: &date_published_datetime_datetime
      method: xpath
      pattern: //meta[@itemprop="datePublished"]/@datetime
    date_published_content: &date_published_content_datetime
      method: xpath
      pattern: //meta[@itemprop="datePublished"]/@content
  title:
    html: &html_title
      method: "xpath"
      pattern: "//title"
    og: &og_title
      method: "xpath"
      pattern: "//meta[@property='og:title']/@content"
    metainspector: &metainspector_title
      method: 'metainspector'
      pattern: :best_title

domains:
  investors.com:
    author: *rel_link_author
    body:
      method: "css"
      pattern: ".single-post-content"
    description: *og_description
    keywords: *meta_keywords
    section: *meta_section
    datetime: *article_published_time_datetime
    title: *og_title
  fool.com:
    author: *meta_author
    body: *readability_body
    description: *meta_description
    keywords: *article_tag_keywords
    section: *meta_section
    datetime: *date_datetime
    title: *og_title
