# All domains must include the scrape pattern for data_types: :required

data_types:
  required:
    - body
    - description
    - keywords
    - section
    - time
    - title

# All data types must include :method and :pattern
#
presets:
  description:
    meta: &meta_description
      method: "xpath"
      pattern: "//meta[@name='description']/@content"
    og: &og_description
      method: "xpath"
      pattern: "//meta[@property='og:description']/@content"
  keywords:
    meta: &meta_keywords
      method: "xpath"
      pattern: "//meta[@name='keywords']/@content"
  section:
    meta: &meta_section
      method: "xpath"
      pattern: "//meta[@property='article:section']/@content"
  time:
    published: &published_time
      method: "xpath"
      pattern: "//meta[@property='article:published_time']/@content"
  title:
    html: &html_title
      method: "xpath"
      pattern: "//title"
    og: &og_title
      method: "xpath"
      pattern: "//meta[@property='og:title']/@content"

domains:
  investors.com:
    body:
      method: "css"
      pattern: ".single-post-content"
    description: *og_description
    keywords: *meta_keywords
    section: *meta_section
    time: *published_time
    title: *og_title
