# All domains should include the scrape method/pattern for data_types

data_types:
  - "author"
  - "body"
  - "description"
  - "keywords"
  - "section"
  - "datetime"
  - "title"

# All data types must include :method and :pattern
#
presets:
  author:
    class: &class_author
      method: xpath
      pattern: "//*[contains(concat(' ', @class, ' '), 'author')]"
    id: &id_author
      method: xpath
      pattern: "//*[@id='author']"
    name: &name_author
      method: xpath
      pattern: "//*[@class='author-name']"
    link: &link_author
      method: xpath
      pattern: "//a[contains(concat(' ', @href, ' '), 'author')"
    meta: &meta_author
      method: xpath
      pattern: "//meta[@name='author']/@content"
    rel_link: &rel_link_author
      method: xpath
      pattern: "//a[@rel='author']"
    vcard: &vcard_author
      method: xpath
      pattern: "//*[contains(@class, 'vcard')]//*[contains(@class, 'fn')]"
  body:
    readability: &readability
      method: "readability"
      pattern: ""
  description:
    meta: &meta_description
      method: "xpath"
      pattern: "//meta[@name='description']/@content"
    og: &og_description
      method: "xpath"
      pattern: "//meta[@property='og:description']/@content"
  keywords:
    meta: &meta_keywords
      method: "xpath"
      pattern: "//meta[@name='keywords']/@content"
    article_tag: &article_tag
      method: "xpath"
      pattern: "//meta[@property='article:tag']/@content"
  section:
    meta: &meta_section
      method: "xpath"
      pattern: "//meta[@property='article:section']/@content"
  datetime:
    article_date_original: &article_date_original
      method: xpath
      pattern: //meta[@name='article_date_original']/@content
    article_published_time: &article_published_time
      method: "xpath"
      pattern: "//meta[@property='article:published_time']/@content"
    date: &date
      method: xpath
      pattern: //meta[@name='date']/@content
    date_published: &date_published
      method: xpath
      pattern: //meta[@itemprop='datePublished']/@datetime
    og_published_time: &og_published_time
      method: xpath
      pattern: //meta[@property='og:published_time']/@content
    original_publication_date: &original_publication_date
      method: xpath
      pattern: //meta[@name='OriginalPublicationDate']/@content
    publication_date: &publication_date
      method: xpath
      pattern: //meta[@name='publication_date']/@content
    publish_date: &publish_date
      method: xpath
      pattern: //meta[@name='PublishDate']/@content
    rnews_datePublished: &rnews_datePublished
      method: xpath
      pattern: //meta[@property='rnews:datePublished']/@content
    sailthru_date: &sailthru_date
      method: xpath
      pattern: //meta[@name='sailthru.date']/@content
  title:
    html: &html_title
      method: "xpath"
      pattern: "//title"
    og: &og_title
      method: "xpath"
      pattern: "//meta[@property='og:title']/@content"

domains:
  investors.com:
    author: *rel_link_author
    body:
      method: "css"
      pattern: ".single-post-content"
    description: *og_description
    keywords: *meta_keywords
    section: *meta_section
    datetime: *article_published_time
    title: *og_title
  fool.com:
    body: *readability
    description: *meta_description
    keywords: *article_tag
    section: *meta_section
    datetime: *date
    title: *og_title
