# All domains should include the scrape method/pattern for data_types

data_types:
  - "body"
  - "description"
  - "keywords"
  - "section"
  - "datetime"
  - "title"

# All data types must include :method and :pattern
#
presets:
  body:
    readability: &readability
      method: "readability"
      pattern: ""
  description:
    meta: &meta_description
      method: "xpath"
      pattern: "//meta[@name='description']/@content"
    og: &og_description
      method: "xpath"
      pattern: "//meta[@property='og:description']/@content"
  keywords:
    meta: &meta_keywords
      method: "xpath"
      pattern: "//meta[@name='keywords']/@content"
    article_tag: &article_tag
      method: "xpath"
      pattern: "//meta[@property='article:tag']/@content"
  section:
    meta: &meta_section
      method: "xpath"
      pattern: "//meta[@property='article:section']/@content"
  datetime:
    published: &published_time
      method: "xpath"
      pattern: "//meta[@property='article:published_time']/@content"
    date: &date
      method: xpath
      pattern: //meta[@name='date']/@content
  title:
    html: &html_title
      method: "xpath"
      pattern: "//title"
    og: &og_title
      method: "xpath"
      pattern: "//meta[@property='og:title']/@content"

domains:
  investors.com:
    body:
      method: "css"
      pattern: ".single-post-content"
    description: *og_description
    keywords: *meta_keywords
    section: *meta_section
    datetime: *published_time
    title: *og_title
  fool.com:
    body: *readability
    description: *meta_description
    keywords: *article_tag
    section: *meta_section
    datetime: *date
    title: *og_title
